import os
from os import path as osp
import sys
sys.path.insert(0, osp.abspath('../scripts'))
from scons_lib import set_env, compile, bin2hex

main = 'riscv_tests'

srcs = [i for i in os.listdir('src') if i.endswith('.s') and i not in [f'{main}.s', 'dummy_init.s', 'init.s']]
names = [osp.splitext(osp.basename(i))[0] for i in srcs]


objs = []
env = set_env(Environment())

for name in names:
    obj = f'out/{name}.o'
    objs.append(obj)
    compile(obj)

compile('out/riscv_tests.o')
compile('out/dummy_init.o')

env.Command(f'bin/{main}', ['src/link.lds', 'out/riscv_tests.o'] + objs, 'riscv-none-elf-ld --gc-sections -o ${TARGET} -T ${SOURCES}')
env.Command(f'bin/{main}.hex', [f'bin/{main}', '../scripts/gen_text.py'], '../scripts/gen_text.py ${SOURCE} > ${TARGET}')

env.Command('dis', f'bin/{main}', 'riscv-none-elf-objdump.exe -d ${SOURCE} -M numeric')
env.Command('clean', '', f'rm -rf bin out')

Default([f'bin/{main}.hex'])