import os
from os import path as osp
import sys
sys.path.insert(0, osp.abspath('../scripts'))
from scons_lib import set_env, compile, bin2hex

main = 'boot'

srcs = ['boot.s']
names = [osp.splitext(osp.basename(i))[0] for i in srcs]

objs = []
env = set_env(Environment())

for name in names:
    obj = f'out/{name}.o'
    objs.append(obj)
    compile(obj)

env.Command(f'bin/{main}', ['src/link.lds'] + objs, 'riscv-none-elf-ld --gc-sections -o ${TARGET} -T ${SOURCES}')
env.Command(f'bin/{main}_text.bin', f'bin/{main}', 'riscv-none-elf-objcopy -O binary -j .text ${SOURCE} ${TARGET}')
bin2hex(f'bin/{main}_text.bin')

env.Command('dis', f'bin/{main}', 'riscv-none-elf-objdump.exe -d ${SOURCE}')
env.Command('disn', f'bin/{main}', 'riscv-none-elf-objdump.exe -d ${SOURCE} -M numeric')
env.Command('clean', '', f'rm -rf out bin')

Default([f'bin/{main}_text.hex'])